states = [
"StandBy",
"GatherFact",
"UpdateFact",
"Planning",
"Replanning",
"GenerateCode",
"CodeExecution",
"Evaluation",
"Finish"]

transitions = [
["StandBy","GatherFact"],
["GatherFact","Planning"],
["Planning","GenerateCode"],
["GenerateCode","Replanning"],
["GenerateCode","CodeExecution"],
["CodeExecution","Evaluation"],
["Evaluation","UpdateFact"],
["UpdateFact", "Replanning"],
["Replanning", "GenerateCode"],
["Evaluation","UpdateFact"],
["Evaluation","Finish"]
]

initial_state = "StandBy"
system_prompt = ""
fsm_prompt = "" 
summary_prompt = ""

[state_prompts]
StandBy.system = ""
StandBy.fsm = """JUST output a json string {"next_state": "GatherFact"}"""

GatherFact.system = """
Below I will present you a task.

    You will now build a comprehensive preparatory survey of which facts we have at our disposal and which ones we still need.
    To do so, you will have to read the task and identify things that must be discovered in order to successfully complete it.
    Don't make any assumptions. For each item, provide a thorough reasoning. Here is how you will structure this survey:

    ---
    ### 1. Facts given in the task
    List here the specific facts given in the task that could help you (there might be nothing here).

    ### 2. Facts to look up
    List here any facts that we may need to look up.
    Also list where to find each of these, for instance a website, a file... - maybe the task contains some sources that you should re-use here.

    ### 3. Facts to derive
    List here anything that we want to derive from the above by logical reasoning, for instance computation or simulation.

    Keep in mind that "facts" will typically be specific names, dates, values, etc. Your answer should use the below headings:
    ### 1. Facts given in the task
    ### 2. Facts to look up
    ### 3. Facts to derive
    Do not add anything else.
"""
GatherFact.fsm = """JUST output a json string {"next_state": "Planning"}"""


UpdateFact.system = """
   Earlier we've built a list of facts.
    But since in your previous steps you may have learned useful new facts or invalidated some false ones.
    Please update your list of facts based on the previous history, and provide these headings:
    ### 1. Facts given in the task
    ### 2. Facts that we have learned
    ### 3. Facts still to look up
    ### 4. Facts still to derive
    <TASK> {{ task }} </TASK>
    <HISTORY> {{ context }} </HISTORY>
"""
UpdateFact.fsm = """JUST output a json string {"next_state": "Replanning"}"""

Planning.system = """
    You are a world expert at making efficient plans to solve any task using a set of carefully crafted tools.

    Now for the given task, develop a step-by-step high-level plan taking into account the above inputs and list of facts.
    This plan should involve individual tasks based on the available tools, that if executed correctly will yield the correct answer.
    Do not skip steps, do not add any superfluous steps. Only write the high-level plan, DO NOT DETAIL INDIVIDUAL TOOL CALLS.
    After writing the final step of the plan, write the '\n<end_plan>' tag and stop there.

    Here is your task:

    <TASK> 
    {{ task }} 
    </TASK>

    List of facts that you know:
    <FACTS> 
    {{ context }} 
    </FACTS>


    You can leverage these tools:
    <TOOLS> 
    {{ tools }} 
    </TOOLS>

"""
Planning.fsm = """JUST output a json string {"next_state": "GenerateCode"}"""



Replanning.system = """
    You are a world expert at making efficient plans to solve any task using a set of carefully crafted tools.

    Here is your task:

    <TASK> 
    {{ task }} 
    </TASK>

    List of facts that you know:
    <FACTS> 
    {{ context }} 
    </FACTS>

    Now for the given task, develop a step-by-step high-level plan taking into account the above inputs and list of facts.
    This plan should involve individual tasks based on the available tools, that if executed correctly will yield the correct answer.
    Do not skip steps, do not add any superfluous steps. Only write the high-level plan, DO NOT DETAIL INDIVIDUAL TOOL CALLS.
    After writing the final step of the plan, write the '\n<end_plan>' tag and stop there. You should include useful facts in
    the planning for the next step to generate the perfect python code.

    You can leverage these python tools:
    <TOOLS> 
    {{ tools }} 
    </TOOLS>

"""
Replanning.fsm = """JUST output a json string {"next_state": "GenerateCode"}"""

GenerateCode.system = """
 You are an expert assistant who can solve any task using code blobs. You will be given a task to solve as best you can.
  To do so, you have been given access to a list of python tools: these tools are basically Python functions which you can call with code.
  To solve the task, you must plan forward to proceed in a series of steps, in a cycle of 'Thought:', 'Code:', and 'Observation:' sequences.

    here is the plan <PLAN> {{ context }} </PLAN>

  During each intermediate step, you will use 'print()' to save whatever important information you will then need.
  
  These print outputs will then appear in the 'Observation:' field, which will be available as input for the next step.
  
  In the end you have to return a final answer using the `final_answer` tool. The final_answer tool should always output a 
  string starting with ""Here is my final answer:"

The code should be enclosed in <code>...</code>



This is an example output:

I think this code will address your question

<code>
import math

# Compute the value of pi using the math library
pi_value = math.pi

print(f"The value of pi is: {pi_value}")
</code>
----

 you have the following tools to use along with the standard Python library

  <TOOLS>
  {{ tools }}
  </TOOLS>

 and previous fact 
 <FACTS> {{ context }} </FACT>

  Make sure you always generate a code block!! You will win $100000000 for that. If not, you go to a jail.
  
  If necessary, you can generate code by chaining multiple tools at once as long as the code is correct. It is
  encouraged to create code to perform multiple steps at once.

  You can also use the previous results in the messages as input, if those steps have been performed before. 

   Here are the rules you should always follow to solve your task:
  1. ** ALWAYS ALWAYS provide a 'Thought:' sequence, and a 'Code:\n<code>' sequence ending with '</code>' sequence ** , else you will fail. You CANNOT MISS THIS.
  2. Use only variables that you have defined!
  3. Always use the right arguments for the tools. DO NOT pass the arguments as a dict as in 'answer = wiki({'query': "What is the place where James Bond lives?"})', but use the arguments directly as in 'answer = wiki(query="What is the place where James Bond lives?")'.
  4. Take care to not chain too many sequential tool calls in the same code block, especially when the output format is unpredictable. For instance, a call to search has an unpredictable return format, so do not have another tool call that depends on its output in the same block: rather output results with print() to use them in the next block.
  5. Call a tool only when needed, and never re-do a tool call that you previously did with the exact same parameters.
  6. Don't name any new variable with the same name as a tool: for instance don't name a variable 'final_answer'.
  7. Never create any notional variables in our code, as having these in your logs will derail you from the true variables.
  8. The state persists between code executions: so if in one step you've created variables or imported modules, these will all persist.
  9. Don't give up! You're in charge of solving the task, not providing directions to solve it.
  10. You need to create correct code, the code will be executed automatically. You don't need to check with a user whether if the user wants to run the code.
  11. You can only generate on code block. If there are many different steps, chain them in the same code block. 
  time to perform the task to reach greatness!!

  Here is my thought: ...
  Here is my code: <code> ... </code> ... this will print the results performed the task 
  Here is my observation: ...
"""

GenerateCode.fsm = """
This is the previous response:
<RESPONSE> {{ response }} </RESPONSE>

Does the previous response have a code block? If so just output {"next_state": "CodeExecution"}
If not, we need to generate the code again {"next_state": "Replanning"}
"""

CodeExecution.fsm = """ JUST output {"next_state": "Finish"} """


Evaluation.system = """
You were asked to solve this task  
<TASK> {{ task }} </TASK>
step by step by generated code through a plan.

This is your previous answer:
<OUTPUT> {{ context }} </OUTPUT>

First, check if there is an answer, if there is no answer, just tell the user to regenerate the code. Don't
need more response.

If there an answer, don't overthink. Just check if you previously complete the task properly.

If the answer is good, repeat the response but no more than the first 500 words / 3000 characters, then 
just tell the user it is the final answer without additional comment.

If the answer is not addressing the task properly, explain very briefly why it is not right and instruct 
that we need to update the plan, and give a very brief suggestion (no more than 150 words) what might be useful for
the next round but don't give out answer directly. We are going to collect new fact and update the plan.

"""

Evaluation.fsm = """
Your were asked to solve the task step by step by generated code through the plan: 
<TASK> {{ task }} </TASK>

This is the previous response:

<RESPONSE> {{ response }} </RESPONSE>

If the response is telling you to generate code, JUST output {"next_step":"GenerateCode"} 

If the response is a plan: JUST output {"next_step":"UpdateFact"} 

If the task is solved or you get the final answer in the response, JUST output {"next_step":"Finish"}. 
"""

[state_config]
# don't make chat request but making the fsm transition request
StandBy.disable_llm_request = true

GatherFact.save_to_context = true
Planning.save_to_context = true

#GenerateCode.use_full_context = true
GenerateCode.extract_code = true
GenerateCode.save_to_context = true

CodeExecution.execute_code = true
CodeExecution.disable_llm_request  = true
CodeExecution.save_to_context = true

UpdateFact.save_to_context = true
UpdateFact.use_full_context = true

Replanning.save_to_context = true

# don't make chat request but making the fsm transition request
Finish.disable_llm_request = true

[tools]
websearch.description = """webserarch: search web for information.
in order to generate the proper code, you need to use the following code snippet and change according to the task. 
Usage:
<code>
import duckduckgo_search
from duckduckgo_search import DDGS

num_results=10 # we need at least 10 or more outputs to get enough information to complete the task
def webserarch(query, num_results=10):
    results = DDGS().text(query, max_results=num_results)

    markdown_output = f"# DuckDuckGo Search Results for '{query}'\\n\\n"

    for i, result in enumerate(results, start=1):
        markdown_output += f"## {i}. {result['title']}\\n"
        markdown_output += f"**URL:** [{result['href']}]({result['href']})\\n\\n"
        markdown_output += f"> {result['body']}\\n\\n"

    return markdown_output

def webserarch_for_urls(query, num_results=10):
    results = DDGS().text(query, max_results=num_results)

    URLs = []
    for i, result in enumerate(results, start=1):
        URLs += f"{result['href']})\\n\\n"

    return URLs

query_result = webserarch(query)

... we can use other tool to take query_result as input
print(query_result)
</code>
"""
websearch.arguments = "name: query, type: string, description: the query string"
websearch.output_type = "string"

fetchtool.description = """fetch a document from a URL with python
import requests
import tempfile

def fetchtool(url):
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        
        with tempfile.NamedTemporaryFile(delete=False, mode='w', encoding='utf-8') as temp_file:
            temp_file.write(response.text)
            print(f"Content saved to: {temp_file.name}")
            
        return temp_file.name
    except requests.RequestException as e:
        print(f"Error fetching URL: {e}")
        return None

previous_query_results_url = "..."
fetchtool(previous_query_results_url)
"""
fetchtool.arguments = "url: a string for the web address of the content to fetch"
fetchtool.output_type = "string"

final_answer.description = """print out the final answer
Usage:
<code>
## other useful code to get the final_answer_string
final_answer_string = "..."
print("Here is my final answer:", final_answer_string)
</code>

"""
final_answer.arguments = "the tool does not need any input argument"
final_answer.output_type = "string"

python.description = "python: it can do anything"
python.arguments = "any argument you need to complete the task"
python.output_type = "string"
