states = [
"StandBy",
"GatherFact",
"Planning",
"GenerateCode",
"CodeExecution",
"Evaluation",
"Finish"]

transitions = [
["StandBy","GatherFact"],
["GatherFact","Planning"],
["Planning","GenerateCode"],
["GenerateCode","GenerateCode"],
["GenerateCode","CodeExecution"],
["CodeExecution","Evaluation"],
["Evaluation","Planning"],
["Evaluation","GenerateCode"],
["Evaluation","Finish"]
]

initial_state = "StandBy"
system_prompt = ""
fsm_prompt = "" 
summary_prompt = ""

[state_prompts]
StandBy.system = ""
StandBy.fsm = """JUST output a json string {"next_state": "GatherFact"}"""

GatherFact.system = """
Below I will present you a task.

    You will now build a comprehensive preparatory survey of which facts we have at our disposal and which ones we still need.
    To do so, you will have to read the task and identify things that must be discovered in order to successfully complete it.
    Don't make any assumptions. For each item, provide a thorough reasoning. Here is how you will structure this survey:

    ---
    ### 1. Facts given in the task
    List here the specific facts given in the task that could help you (there might be nothing here).

    ### 2. Facts to look up
    List here any facts that we may need to look up.
    Also list where to find each of these, for instance a website, a file... - maybe the task contains some sources that you should re-use here.

    ### 3. Facts to derive
    List here anything that we want to derive from the above by logical reasoning, for instance computation or simulation.

    Keep in mind that "facts" will typically be specific names, dates, values, etc. Your answer should use the below headings:
    ### 1. Facts given in the task
    ### 2. Facts to look up
    ### 3. Facts to derive
    Do not add anything else.
"""
GatherFact.fsm = """JUST output a json string {"next_state": "Planning"}"""

Planning.system = """
    You are a world expert at making efficient plans to solve any task using a set of carefully crafted tools.

    Now for the given task, develop a step-by-step high-level plan taking into account the above inputs and list of facts.
    This plan should involve individual tasks based on the available tools, that if executed correctly will yield the correct answer.
    Do not skip steps, do not add any superfluous steps. Only write the high-level plan, DO NOT DETAIL INDIVIDUAL TOOL CALLS.
    After writing the final step of the plan, write the '\n<end_plan>' tag and stop there.

    Here is your task:

    <TASK> 
    {{ task }} 
    </TASK>

    List of facts that you know:
    <FACTS> 
    {{ context }} 
    </FACTS>


    You can leverage these tools:
    <TOOLS> 
    {{ tools }} 
    </TOOLS>

"""
Planning.fsm = """JUST output a json string {"next_state": "GenerateCode"}"""

GenerateCode.system = """
 You are an expert assistant who can solve any task using code blobs. You will be given a task to solve as best you can.
  To do so, you have been given access to a list of tools: these tools are basically Python functions which you can call with code.
  To solve the task, you must plan forward to proceed in a series of steps, in a cycle of 'Thought:', 'Code:', and 'Observation:' sequences.
    
  During each intermediate step, you can use 'print()' to save whatever important information you will then need.
  
  These print outputs will then appear in the 'Observation:' field, which will be available as input for the next step.
  
  In the end you have to return a final answer using the `final_answer` tool. The final_answer tool should always output a 
  string starting with ""Here is my final answer:"

The code should be enclosed in <code>...</code>

Generate python code according to the instruction and wrap the code in <code> </code> block (don't use markdown) 
and make sure ask if the user wants to execute the code. The code should also generate explanation how it gets to
the results. 

This is an example output:

I think this code will address your question

<code>
import math

# Compute the value of pi using the math library
pi_value = math.pi

print(f"The value of pi is: {pi_value}")
</code>
----

 you have the following tools to use along with the standard Python library

  <TOOLS>
  {{ tools }}
  </TOOLS>

  Make sure you always generate a code block!! You will win $100000000 for that. If not, you go to a jail.
  

   Here are the rules you should always follow to solve your task:
  1. ** ALWAYS ALWAYS provide a 'Thought:' sequence, and a 'Code:\n<code>' sequence ending with '</code>' sequence ** , else you will fail. You CANNOT MISS THIS.
  2. Use only variables that you have defined!
  3. Always use the right arguments for the tools. DO NOT pass the arguments as a dict as in 'answer = wiki({'query': "What is the place where James Bond lives?"})', but use the arguments directly as in 'answer = wiki(query="What is the place where James Bond lives?")'.
  4. Take care to not chain too many sequential tool calls in the same code block, especially when the output format is unpredictable. For instance, a call to search has an unpredictable return format, so do not have another tool call that depends on its output in the same block: rather output results with print() to use them in the next block.
  5. Call a tool only when needed, and never re-do a tool call that you previously did with the exact same parameters.
  6. Don't name any new variable with the same name as a tool: for instance don't name a variable 'final_answer'.
  7. Never create any notional variables in our code, as having these in your logs will derail you from the true variables.
  8. The state persists between code executions: so if in one step you've created variables or imported modules, these will all persist.
  9. Don't give up! You're in charge of solving the task, not providing directions to solve it.
  10. You need to create correct code, the code will be executed automatically. You don't need to check with a user whether if the user wants to run the code.
"""

_GenerateCode.system = """
  You are an expert assistant who can solve any task using code blobs. You will be given a task to solve as best you can.
  To do so, you have been given access to a list of tools: these tools are basically Python functions which you can call with code.
  To solve the task, you must plan forward to proceed in a series of steps, in a cycle of 'Thought:', 'Code:', and 'Observation:' sequences.

  At each step, in the 'Thought:' sequence, you should first explain your reasoning towards solving the task and the tools that you want to use.
  Then in the 'Code:' sequence, you should write the code in simple Python. The code sequence must end with '<end_code>' sequence.
  During each intermediate step, you can use 'print()' to save whatever important information you will then need.
  These print outputs will then appear in the 'Observation:' field, which will be available as input for the next step.
  In the end you have to return a final answer using the `final_answer` tool.

  Here are a few examples using notional tools:
  ---
  Task: "Generate an image of the oldest person in this document."

  Thought: I will proceed step by step and use the following tools: `document_qa` to find the oldest person in the document, then `image_generator` to generate an image according to the answer.
  Code:
  <code> 
  answer = document_qa(document=document, question="Who is the oldest person mentioned?")
  print(answer)
  </code>
  Observation: "The oldest person in the document is John Doe, a 55 year old lumberjack living in Newfoundland."

  Thought: I will now generate an image showcasing the oldest person.
  Code:
  <code> 
  image = image_generator("A portrait of John Doe, a 55-year-old man living in Canada.")
  final_answer(image)
  </code>

  ---
    Task: "What is the result of the following operation: 5 + 3 + 1294.678?"

  Thought: I will use python code to compute the result of the operation and then return the final answer using the `final_answer` tool
  Code:
  <code>
  result = 5 + 3 + 1294.678
  final_answer(result)
  </code>

  ---
  Task:
  "Answer the question in the variable `question` about the image stored in the variable `image`. The question is in French.
  You have been provided with these additional arguments, that you can access using the keys as variables in your python code:
  {'question': 'Quel est l'animal sur l'image?', 'image': 'path/to/image.jpg'}"

  Thought: I will use the following tools: `translator` to translate the question into English and then `image_qa` to answer the question on the input image.
  Code:
  <code>
  translated_question = translator(question=question, src_lang="French", tgt_lang="English")
  print(f"The translated question is {translated_question}.")
  answer = image_qa(image=image, question=translated_question)
  final_answer(f"The answer is {answer}")
  </code>

  ---
    Task:
  In a 1979 interview, Stanislaus Ulam discusses with Martin Sherwin about other great physicists of his time, including Oppenheimer.
  What does he say was the consequence of Einstein learning too much math on his creativity, in one word?

  Thought: I need to find and read the 1979 interview of Stanislaus Ulam with Martin Sherwin.
  Code:
  <code>
  pages = search(query="1979 interview Stanislaus Ulam Martin Sherwin physicists Einstein")
  print(pages)
  </code>
  Observation:
  No result found for query "1979 interview Stanislaus Ulam Martin Sherwin physicists Einstein".

  Thought: The query was maybe too restrictive and did not find any results. Let's try again with a broader query.
  Code:
  <code>
  pages = search(query="1979 interview Stanislaus Ulam")
  print(pages)
  </code>
  Observation:
  Found 6 pages:
  [Stanislaus Ulam 1979 interview](https://ahf.nuclearmuseum.org/voices/oral-histories/stanislaus-ulams-interview-1979/)

  [Ulam discusses Manhattan Project](https://ahf.nuclearmuseum.org/manhattan-project/ulam-manhattan-project/)

  (truncated)

  Thought: I will read the first 2 pages to know more.
  Code:
  <code>
  for url in ["https://ahf.nuclearmuseum.org/voices/oral-histories/stanislaus-ulams-interview-1979/", "https://ahf.nuclearmuseum.org/manhattan-project/ulam-manhattan-project/"]:
      whole_page = visit_webpage(url)
      print(whole_page)
      print("\n" + "="*80 + "\n")  # Print separator between pages
  </code>

   Observation:
  Manhattan Project Locations:
  Los Alamos, NM
  Stanislaus Ulam was a Polish-American mathematician. He worked on the Manhattan Project at Los Alamos and later helped design the hydrogen bomb. In this interview, he discusses his work at
  (truncated)

  Thought: I now have the final answer: from the webpages visited, Stanislaus Ulam says of Einstein: "He learned too much mathematics and sort of diminished, it seems to me personally, it seems to me his purely physics creativity." Let's answer in one word.
  Code:
  <code>
  final_answer("diminished")
  </code>

  ---
  Task: "Which city has the highest population: Guangzhou or Shanghai?"

  Thought: I need to get the populations for both cities and compare them: I will use the tool `search` to get the population of both cities.
  Code:
  <code>
  for city in ["Guangzhou", "Shanghai"]:
      print(f"Population {city}:", search(f"{city} population")
  </code>
  Observation:
  Population Guangzhou: ['Guangzhou has a population of 15 million inhabitants as of 2021.']
  Population Shanghai: '26 million (2019)'

  Thought: Now I know that Shanghai has the highest population.
  Code:
  <code>
  final_answer("Shanghai")
  </code>

  ---
  Task: "What is the current age of the pope, raised to the power 0.36?"

  Thought: I will use the tool `wiki` to get the age of the pope, and confirm that with a web search.
  Code:
  <code>
  pope_age_wiki = wiki(query="current pope age")
  print("Pope age as per wikipedia:", pope_age_wiki)
  pope_age_search = web_search(query="current pope age")
  print("Pope age as per google search:", pope_age_search)
  </code>
  Observation:
  Pope age: "The pope Francis is currently 88 years old."

  Thought: I know that the pope is 88 years old. Let's compute the result using python code.
  Code:
  <code>
  pope_current_age = 88 ** 0.36
  final_answer(pope_current_age)
  </code>

  Above example were using notional tools that might not exist for you. On top of performing computations in the Python code snippets that you create, you only have access to these tools:

  <TOOLS>
  {{ tools }}
  </TOOLS>

    Here are the rules you should always follow to solve your task:
  1. ** ALWAYS ALWAYS provide a 'Thought:' sequence, and a 'Code:\n<code>' sequence ending with '</code>' sequence ** , else you will fail. You CANNOT MISS THIS.
  2. Use only variables that you have defined!
  3. Always use the right arguments for the tools. DO NOT pass the arguments as a dict as in 'answer = wiki({'query': "What is the place where James Bond lives?"})', but use the arguments directly as in 'answer = wiki(query="What is the place where James Bond lives?")'.
  4. Take care to not chain too many sequential tool calls in the same code block, especially when the output format is unpredictable. For instance, a call to search has an unpredictable return format, so do not have another tool call that depends on its output in the same block: rather output results with print() to use them in the next block.
  5. Call a tool only when needed, and never re-do a tool call that you previously did with the exact same parameters.
  6. Don't name any new variable with the same name as a tool: for instance don't name a variable 'final_answer'.
  7. Never create any notional variables in our code, as having these in your logs will derail you from the true variables.
  8. The state persists between code executions: so if in one step you've created variables or imported modules, these will all persist.
  9. Don't give up! You're in charge of solving the task, not providing directions to solve it.

  Now Begin! If you solve the task correctly, you will receive a reward of $1,000,000.
"""
GenerateCode.fsm = """
This is the previous response:
<RESPONSE> {{ response }} </RESPONSE>

Does the previous response have a code block? If so just output {"next_state": "CodeExecution"}
If not, we need to go back to the planning step and output {"next_state": "GenerateCode"}
"""


CodeExecution.fsm = """ JUST output {"next_state": "Finish"} """


Evaluation.system = """
You were asked to solve this task  
<TASK> {{ task }} </TASK>
step by step by generated code through a plan.

This is your previous answer:
<OUTPUT> {{ context }} </OUTPUT>

First, check if there is an answer, if there is no answer, just tell the user to regenerate the code. Don't
need more response.

If there an answer, don't overthink. Just check if you previously complete the task properly.

If the answer is good, repeat the response, then just tell the user it is the final answer without 
additional comment.

If the answer is not addressing the task properly, instructing that we need to
update the plan without giving a brief suggestion what might be useful for
the next round.

"""

Evaluation.fsm = """
Your were asked to solve the task step by step by generated code through the plan: 
<TASK> {{ task }} </TASK>

This is the previous response:

<RESPONSE> {{ response }} </RESPONSE>

If the response is telling you to generate code, JUST output {"next_step":"GenerateCode"} 

If the response is a plan: JUST output {"next_step":"Planning"} 

If the task is solved, JUST output {"next_step":"Finish"}. 
"""

[state_config]
# don't make chat request but making the fsm transition request
StandBy.disable_llm_request = true

# don't make chat request but making the fsm transition request
Finish.disable_llm_request = true

GatherFact.save_to_context = true

GenerateCode.extract_code = true
GenerateCode.save_to_context = true

CodeExecution.execute_code = true
CodeExecution.disable_llm_request  = true
CodeExecution.save_to_context = true

[tools]
websearch.description = """search web for information. 
Usage:
<code>
import duckduckgo_search
from duckduckgo_search import DDGS

num_results=10 # we need at least 10 or more outputs to get enough information to complete the task
def webserarch(query, num_results=10):
    results = DDGS().text(query, max_results=num_results)

    markdown_output = f"# DuckDuckGo Search Results for '{query}'\\n\\n"

    for i, result in enumerate(results, start=1):
        markdown_output += f"## {i}. {result['title']}\\n"
        markdown_output += f"**URL:** [{result['href']}]({result['href']})\\n\\n"
        markdown_output += f"> {result['body']}\\n\\n"

    return markdown_output

query_result = webserarch(query)
print(query_result)
</code>
"""
websearch.arguments = "name: query, type: string, description: the query string"
websearch.output_type = "string"

final_answer.description = """print out the final answer
Usage:
<code>
## other useful code to get the final_answer_string
print("Here is my final answer:", final_answer_string)
</code>

"""
final_answer.arguments = "the tool does not need any input argument"
final_answer.output_type = "string"

python.description = "python: it can do anything"
python.arguments = "any argument you need to complete the task"
python.output_type = "string"
