#FROM python:3
#RUN pip install requests beautifulsoup4 html2text duckduckgo_search
#RUN apt-get update; apt-get install tesseract-ocr -y
#RUN apt-get install gcc g++ -y
#RUN pip install openparse
#ENTRYPOINT ["python3"]

FROM ubuntu:latest
RUN apt-get update && apt-get install -y locales curl && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
RUN locale-gen "en_US.UTF-8"
ENV LANG=en_US.utf8
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential zlib1g-dev curl openssl pkg-config libssl-dev python3 python3-pip
RUN apt-get install -y python3.12-venv
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip install requests beautifulsoup4 html2text duckduckgo_search openparse
ENTRYPOINT ["/opt/venv/bin/python3"]
